apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: loki
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: loki
            namespace: monitoring

  template:
    metadata:
      name: monitoring-loki
      annotations:
    spec:
      project: default

      source:
        repoURL: https://github.com/PainApplee/k8s-monitoring-gitops.git
        targetRevision: main
        path: monitoring/charts/loki

        helm:
          values: |
            loki:
              auth_enabled: false

              commonConfig:
                replication_factor: 1

              storage:
                type: filesystem
                bucketNames:
                  chunks: chunks
                  ruler: ruler
                  admin: admin

              schemaConfig:
                configs:
                  - from: 2024-01-01
                    store: tsdb
                    object_store: filesystem
                    schema: v13
                    index:
                      prefix: loki_index_
                      period: 24h

              singleBinary:
                replicas: 1

              resources:
                requests:
                  cpu: 50m
                  memory: 256Mi
                limits:
                  memory: 512Mi

      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
