apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: loki
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: loki
            namespace: monitoring

  template:
    metadata:
      name: loki
      annotations:
        argocd.argoproj.io/sync-wave: "3"
    spec:
      project: default
    

      source:
        repoURL: https://github.com/PainApplee/k8s-monitoring-gitops.git
        targetRevision: main
        path: monitoring/charts/loki

      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
